apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lugn-trygg.fullname" . }}-config
data:
  NODE_ENV: "production"
  API_BASE_URL: {{ .Values.frontend.env.apiUrl | quote }}
  FRONTEND_DOMAIN: {{ .Values.global.domain.app | quote }}
  CDN_URL: {{ .Values.frontend.env.cdnUrl | quote }}
  BACKEND_PORT: {{ .Values.backend.service.port | quote }}
  REDIS_HOST: {{ .Values.backend.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.backend.env.redisPort | quote }}
  RATE_LIMIT_WINDOW: "60"
  RATE_LIMIT_MAX: "1000"
