apiVersion: v1
kind: Service
metadata:
  name: {{ include "lugn-trygg.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "lugn-trygg.name" . }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "lugn-trygg.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
