{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lugn-trygg.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "lugn-trygg.name" . }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "lugn-trygg.name" . }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
{{- end }}
