apiVersion: v1
kind: Service
metadata:
  name: {{ include "lugn-trygg.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "lugn-trygg.name" . }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "lugn-trygg.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
